using System.Collections.ObjectModel;
using System.Windows.Input;
using TastyMealPlanner.Helpers;
using TastyMealPlanner.Models;
using TastyMealPlanner.Services;

namespace TastyMealPlanner.ViewModels;

/// <summary>Manages the shopping list with automatic ingredient generation from today's meal plan.</summary>
public class ShoppingListViewModel : BaseViewModel
{
    private readonly IDataService _dataService;
    private readonly IHapticService _haptic;

    /// <summary>Gets the collection of shopping list items (auto-generated and manual).</summary>
    public ObservableCollection<ShoppingItem> Items { get; } = new();

    private string _newItemName = string.Empty;
    /// <summary>Gets or sets the name of a new item to add to the shopping list.</summary>
    public string NewItemName
    {
        get => _newItemName;
        set
        {
            if (SetProperty(ref _newItemName, value))
                ValidationError = null;
        }
    }

    private string _newItemQuantity = string.Empty;
    /// <summary>Gets or sets the quantity of a new item to add to the shopping list.</summary>
    public string NewItemQuantity
    {
        get => _newItemQuantity;
        set
        {
            if (SetProperty(ref _newItemQuantity, value))
                ValidationError = null;
        }
    }

    private string? _validationError;
    /// <summary>Gets or sets the current validation error message for the add-item form.</summary>
    public string? ValidationError
    {
        get => _validationError;
        set => SetProperty(ref _validationError, value);
    }

    /// <summary>Command to validate and add a new item to the shopping list.</summary>
    public ICommand AddItemCommand { get; }
    /// <summary>Command to toggle the checked (purchased) state of a shopping item.</summary>
    public ICommand ToggleItemCommand { get; }
    /// <summary>Command to remove all checked (purchased) items from the shopping list.</summary>
    public ICommand ClearCheckedCommand { get; }

    /// <summary>Initialises a new instance of the <see cref="ShoppingListViewModel"/> class with data and haptic services, then loads the shopping list.</summary>
    public ShoppingListViewModel(IDataService dataService, IHapticService haptic)
    {
        _dataService = dataService;
        _haptic = haptic;
        Title = "Shopping List";

        AddItemCommand = new Command(OnAddItem);
        ToggleItemCommand = new Command<ShoppingItem>((item) =>
        {
            if (item != null)
            {
                _haptic.PerformClick();
                _dataService.ToggleShoppingItem(item.Id);
            }
        });

        ClearCheckedCommand = new Command(async () =>
        {
            _haptic.PerformLongPress();
            var checkedItems = Items.Count(i => i.IsChecked);
            if (checkedItems == 0)
            {
                ValidationError = "No items are checked to clear.";
                return;
            }
            bool confirm = await Shell.Current.DisplayAlert(
                "Clear Items", $"Remove {checkedItems} purchased item(s)?", "Yes", "No");
            if (confirm)
            {
                _dataService.ClearCheckedShoppingItems();
                LoadItems();
                ValidationError = null;
            }
        });

        LoadItems();
    }

    /// <summary>Validates and adds a new item to the shopping list.</summary>
    private async void OnAddItem()
    {
        var (isValid, error) = ValidationHelper.ValidateShoppingItem(NewItemName, NewItemQuantity);
        if (!isValid)
        {
            _haptic.PerformLongPress();
            ValidationError = error;
            return;
        }

        _haptic.PerformClick();
        try
        {
            _dataService.AddShoppingItem(new ShoppingItem
            {
                Name = NewItemName.Trim(),
                Quantity = NewItemQuantity.Trim(),
                IsAutoGenerated = false
            });

            NewItemName = string.Empty;
            NewItemQuantity = string.Empty;
            ValidationError = null;
            LoadItems();
        }
        catch (Exception ex)
        {
            ValidationError = $"Could not add item: {ex.Message}";
        }
    }

    /// <summary>Reloads the shopping list, regenerating auto items from today's meal plan.</summary>
    public void LoadItems()
    {
        // Remove old auto-generated items, regenerate from today's meal plan
        _dataService.RemoveAutoGeneratedItems();

        var today = DateTime.Now.DayOfWeek;
        var monday = DateTime.Now.AddDays(-(int)today + 1);
        var todayMeals = _dataService.GetMealPlanForWeek(monday)
            .Where(e => e.Day == today && e.Recipe != null);

        foreach (var meal in todayMeals)
        {
            foreach (var ingredient in meal.Recipe!.Ingredients)
            {
                var parts = ingredient.Split(' ', 2);
                var qty = parts.Length > 1 ? parts[0] : "";
                var name = parts.Length > 1 ? parts[1] : ingredient;

                _dataService.AddShoppingItem(new ShoppingItem
                {
                    Name = char.ToUpper(name[0]) + name[1..],
                    Quantity = qty,
                    IsAutoGenerated = true
                });
            }
        }

        // Display all items: auto first, then manual; unchecked first
        Items.Clear();
        foreach (var item in _dataService.GetShoppingList()
            .OrderBy(i => i.IsAutoGenerated ? 0 : 1)
            .ThenBy(i => i.IsChecked ? 1 : 0))
            Items.Add(item);
    }
}
