using TastyMealPlanner.Models;

namespace TastyMealPlanner.Services;

public interface IDataService
{
    List<Recipe> GetAllRecipes();

    List<Recipe> GetRecipesByCategory(FoodCategory category);

    Recipe? GetRecipeById(string id);

    List<MealPlanEntry> GetMealPlanForWeek(DateTime weekStart);

    List<ShoppingItem> GetShoppingList();

    void AddToMealPlan(MealPlanEntry entry);

    void RemoveFromMealPlan(string entryId);

    void AddShoppingItem(ShoppingItem item);

    void ToggleShoppingItem(string itemId);

    void ClearCheckedShoppingItems();

    void RemoveAutoGeneratedItems();

    List<Recipe> SearchRecipes(string query);

    void AddRecipe(Recipe recipe);
}
