using TastyMealPlanner.Models;

namespace TastyMealPlanner.Services;

/// <summary>Shopping list management — add, toggle, clear items.</summary>
public interface IShoppingListService
{
    List<ShoppingItem> GetShoppingList();
    void AddShoppingItem(ShoppingItem item);
    void ToggleShoppingItem(string itemId);
    void ClearCheckedShoppingItems();
    void RemoveAutoGeneratedItems();
}
