using TastyMealPlanner.Models;

namespace TastyMealPlanner.Services;

/// <summary>In-memory shopping list with add, toggle, and clear support.</summary>
public class ShoppingListService : IShoppingListService
{
    private readonly List<ShoppingItem> _items = new();

    public List<ShoppingItem> GetShoppingList() => _items;

    public void AddShoppingItem(ShoppingItem item) => _items.Add(item);

    public void ToggleShoppingItem(string itemId)
    {
        var item = _items.FirstOrDefault(i => i.Id == itemId);
        if (item != null)
            item.IsChecked = !item.IsChecked;
    }

    public void ClearCheckedShoppingItems()
        => _items.RemoveAll(i => i.IsChecked);

    public void RemoveAutoGeneratedItems()
        => _items.RemoveAll(i => i.IsAutoGenerated);
}
