using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace TastyMealPlanner.Models;

/// <summary>Represents an item on the shopping list with a name, quantity, and checked state.</summary>
public class ShoppingItem : INotifyPropertyChanged
{
    /// <summary>Unique identifier for the shopping item.</summary>
    public string Id { get; set; } = Guid.NewGuid().ToString();
    /// <summary>Name of the item to purchase.</summary>
    public string Name { get; set; } = string.Empty;
    /// <summary>Quantity or measurement (e.g. "2", "500g").</summary>
    public string Quantity { get; set; } = string.Empty;

    /// <summary>True if this item was auto-generated from today's meal plan ingredients.</summary>
    public bool IsAutoGenerated { get; set; }

    private bool _isChecked;
    public bool IsChecked
    {
        get => _isChecked;
        set
        {
            if (_isChecked != value)
            {
                _isChecked = value;
                OnPropertyChanged();
            }
        }
    }

    /// <summary>Occurs when a property value changes (for UI binding).</summary>
    public event PropertyChangedEventHandler? PropertyChanged;

    protected void OnPropertyChanged([CallerMemberName] string? name = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
}
